# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

name: $(Build.BuildId)

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '12.x'
  displayName: 'Install Node.js'

- task: SonarCloudPrepare@1
  inputs:
    SonarCloud: 'SonarCloud'
    organization: 'twolittlebirds'
    scannerMode: 'CLI'
    configMode: 'manual'
    cliProjectKey: 'TwoLittleBirds_liminal'
    cliProjectName: 'liminal'
    cliSources: '.'
    extraProperties: |
      # Additional properties that will be passed to the scanner, 
      # Put one key=value per line, example:
      sonar.exclusions=**/node_modules/*,**/__tests__/*, **/__tests__/Components/*
      sonar.tests=src
      sonar.test.inclusions=**/*.test.js
      sonar.javascript.lcov.reportPaths=$(System.DefaultWorkingDirectory)/coverage/lcov.info
      sonar.testExecutionReportPaths=$(System.DefaultWorkingDirectory)/test-report.xml

- script: |
    npm install
    npm run build
  displayName: 'npm install and build'

- task: WhiteSource Bolt@20
  inputs:
    advance: true
   
- script: |
    npm run test:ci 
  displayName: 'npm test and coverage'

- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: '**/junit.xml'

- task: PublishCodeCoverageResults@1
  inputs:
    codeCoverageTool: 'Cobertura'
    summaryFileLocation: '$(System.DefaultWorkingDirectory)/coverage/cobertura-coverage.xml'

- task: SonarCloudAnalyze@1

- task: SonarCloudPublish@1
  inputs:
    pollingTimeoutSec: '300'



