# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

name: '$(version).$(Rev:r)'

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '12.x'
  displayName: 'Install Node.js'

- script: |
    npm version patch
    npm install
    npm run build
  displayName: 'npm install and build'

- task: WhiteSource Bolt@20
  inputs:
    advance: true

- task: CopyFiles@2
  inputs:
    SourceFolder: 'build'
    Contents: '**'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
    
- script: |
    CI=true npm run coverage
  displayName: 'npm test and coverage'

- task: PublishTestResults@2
  displayName: 'Publish Test Results junit.xml'
  inputs:
    testResultsFiles: junit.xml

- task: PublishCodeCoverageResults@1
  inputs:
    codeCoverageTool: Cobertura
    summaryFileLocation: $(System.DefaultWorkingDirectory)/coverage/cobertura-coverage.xml

- task: PublishBuildArtifacts@1
  inputs: 
    pathtoPublish: $(Build.ArtifactStagingDirectory) # dist or build files
    ArtifactName: 'drop' # output artifact named drop

